micronaut:
  application:
    name: glomgold
  security:
    authentication: session

jackson:
  serialization:
    writeDatesAsTimestamps: false

endpoints:
  all:
    path: "/management"
    enabled: true
    sensitive: false

netty:
  default:
    allocator:
      max-order: 3

liquibase:
  enabled: true
  datasources:
    liquibase:
      change-log: classpath:db/liquibase-changelog.xml