micronaut:
  application:
    name: glomgold-dev
  views:
    thymeleaf:
      cacheable: true

r2dbc:
  datasources:
    default:
      schema-generate: NONE
      dialect: POSTGRES
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      url: "r2dbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}"

datasources:
  liquibase:
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}"
    maximumPoolSize: 2