name: Glomgold Develop CI
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - 'develop'
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
      - 'release/**'
      - 'support/**'
jobs:
  gradle_dev_build:
    name: Gradle Dev Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.m2/repository
          key: ${{ runner.os }}-gradle-test-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-test-

      - name: Setup GraalVM CE
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.3'
          java-version: '17'
      - name: Install Native Image
        run: gu install native-image

      - name: Running gradle task
        uses: gradle/gradle-build-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          gradle-version: wrapper
          arguments: clean coverageReport sonar
