name: Glomgold Develop CI
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - 'develop'
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
      - 'release/**'
      - 'support/**'
jobs:
  gradle_dev_build:
    name: Gradle Dev Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup GraalVM CE
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Running gradle task
        run: |
          ./gradlew clean :glomgold-webserver:coverageReport sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
